### ISSUE TITLE
使用时会抛出一个sasserror，请问是我少装了什么吗

### ISSUE THREAD

**Issue by PluckySaltyfish** [formilyjs/semi#2]
![image](https://user-images.githubusercontent.com/23007087/180031876-a46554a5-0adc-403a-81ae-66a4d0e22d73.png)

**Comment by prgrmrwy** [comment]
不好意思刚看到，看起来是你的 sass 版本问题，不支持 math.div 用法，你最后解决了么，还需要帮助么
